# Generated by Django 5.1.3 on 2024-11-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
                ('description', models.TextField()),
                ('prix', models.FloatField()),
                ('date_publication', models.DateField(auto_now=True)),
            ],
        ),
    ]
