# Generated by Django 5.1.3 on 2024-11-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0002_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='client',
            new_name='client_commande',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='produit',
            new_name='produit_commande',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='quantite',
            new_name='quantite_commande',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='date_publication',
            new_name='date_expiration_produit',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='description',
            new_name='description_produit',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='nom',
            new_name='nom_produit',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='prix',
            new_name='prix_produit',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='quantite',
            new_name='quantite_produit',
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.CharField(default='kram', max_length=50),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_commande',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_livraison',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='methode_livraison',
            field=models.CharField(default='kram', max_length=50),
        ),
        migrations.AddField(
            model_name='produit',
            name='date_publication_produit',
            field=models.DateField(auto_now=True),
        ),
    ]
