# Generated by Django 5.1.3 on 2024-11-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0003_rename_client_commande_client_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='adresse_livraison',
            field=models.CharField(default='Tunis', max_length=50),
        ),
        migrations.AlterField(
            model_name='commande',
            name='methode_livraison',
            field=models.CharField(default='Express', max_length=50),
        ),
    ]
