# Generated by Django 5.1.3 on 2024-11-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0004_alter_commande_adresse_livraison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_livraison',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_expiration_produit',
            field=models.DateField(),
        ),
    ]
